package DAO;

import java.sql.*;
import Model.Account;
import Model.Message;
import Util.ConnectionUtil;


public class MessageDAO {

    /**
     * Insert a Message into the Message table.
     * The message_id should be automatically generated by the sql database if it is not provided because it was set to auto_increment.
     * Therefore, only the remaining columns (posted_by, message_text, time_posted_epoch) are needed to insert a record.
     * @param message The Message to add to the database.
     * @return Message if successfully persisted, null if not (if the Message primary key was already in use.)
     */
    public Message insertMessage(Message message) {
        Connection connection = ConnectionUtil.getConnection();
        try {
            String sql = "INSERT INTO Message (posted_by, message_text, time_posted_epoch) VALUES (?, ?, ?);" ;
            PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            preparedStatement.setInt(1, message.getPosted_by());
            preparedStatement.setString(2, message.getMessage_text());
            preparedStatement.setLong(3, message.getTime_posted_epoch());
            preparedStatement.executeUpdate();

            ResultSet pkeyResultSet = preparedStatement.getGeneratedKeys();
            if (pkeyResultSet.next()) {
                int generated_message_id = (int)pkeyResultSet.getLong(1);
                return new Message(generated_message_id,
                                   message.getPosted_by(),
                                   message.getMessage_text(),
                                   message.getTime_posted_epoch());
            }
        } catch(SQLException e) {
            System.out.println(e.getMessage());
        }
        return null;
    }
    
    /**
     * Retrieves an Account from the Account table, identified by its username.
     * @return an Account identified by username.
     */
    // public Account getAccountByUsername(String username){
    //     Connection connection = ConnectionUtil.getConnection();
    //     try {
    //         String sql = "SELECT * FROM Account WHERE username = ?;";
    //         PreparedStatement preparedStatement = connection.prepareStatement(sql);

    //         preparedStatement.setString(1, username);

    //         ResultSet rs = preparedStatement.executeQuery();
    //         while (rs.next()) {
    //             Account account = new Account(rs.getInt("account_id"),
    //                                           rs.getString("username"),
    //                                           rs.getString("password"));
    //             return account;
    //         }
    //     } catch (SQLException e) {
    //         System.out.println(e.getMessage());
    //     }
    //     return null;
    // }
}
